#  _____     ___ ____
#   ____|   |    ____|      PSX2 OpenSource Project
#  |     ___|   |____       (C)2002, David Ryan ( Oobles@hotmail.com )
#  ------------------------------------------------------------------------

EE_BIN = ps2vfs.elf
EE_OBJS = main.o hw.o

all: $(EE_BIN)

clean:
	rm -f *.elf *.o *.a

include ../../Makefile.pref
include ../../Makefile.eeglobal
