/*
 * About.java
 *
 * Created on 25. mars 2004, 22:17
 */

package ps2vfs.pluggable.imageconverter;

/**
 *
 * @author  stigpo
 */
public class About extends javax.swing.JDialog {
    
    /** Creates new form About */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

	jButton1.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent e) {
	      closeDialog(null);
	    }
	  });
	jLabel1.setText("<html><h1>Image Converter of PS2Vfs</h1>" +
			"<p>" +
			"Image converter and resizer plugin for PS2Vfs written by " + 
			"Krilon." +
			"<p>" +
			"Thanks to the PS2Reality Team for a great player " +
			"and for making the PS2Vfs open!" + 
			"<p>" + 
			"<p>" + 
			"The Image Converter and Resizer was created to view " +
			"pictures of my son. <BR> " + 
			"Thanks to him (just 3 months now) and to my wife for " + 
			"their patiance." +
			"<p>");
        setLocationRelativeTo(parent);
	pack();
    }
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About Image Converter");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jButton1.setText("OK");
        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        jLabel1.setBorder(new javax.swing.border.EtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new About(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
