#  _____     ___ ____
#   ____|   |    ____|      PSX2 OpenSource Project
#  |     ___|   |____       (C)2002, David Ryan ( Oobles@hotmail.com )
#  ------------------------------------------------------------------------


all: build-ps2vfs 


clean:
	$(MAKE) -C ps2vfs clean
	

build-ps2vfs:
	$(MAKE) -C ps2vfs


