#  _____     ___ ____
#   ____|   |    ____|      PSX2 OpenSource Project
#  |     ___|   |____       (C)2002, David Ryan ( Oobles@hotmail.com )
#  ------------------------------------------------------------------------

all: build-lib build-ps2ip build-ps2ips build-ps2echo build-ps2http


clean:
	$(MAKE) -C bin clean
	$(MAKE) -C lib clean
	$(MAKE) -C ps2ip clean
	$(MAKE) -C ps2ips clean
	$(MAKE) -C ps2echo clean
	$(MAKE) -C ps2http clean


build-lib:
	$(MAKE) -C lib

build-ps2ip:
	$(MAKE) -C ps2ip

build-ps2ips:
	$(MAKE) -C ps2ips

build-ps2echo:
	$(MAKE) -C ps2echo

build-ps2http:
	$(MAKE) -C ps2http


